***********************************************************************************
Fecha / Hora : 2022/12/27 17:17:51
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:17:52
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb241f610>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:17:52
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:17:52
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:18:52
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:18:52
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb241f870>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:18:52
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:18:52
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:19:52
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:19:52
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb24329b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:19:52
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:19:52
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:20:52
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:20:52
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb24321d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:20:53
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:20:53
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:21:53
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:21:53
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb241f0f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:21:53
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:21:53
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:22:53
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:22:53
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb24323b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:22:53
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:22:53
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:24:29
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:24:29
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb2476dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:24:29
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:24:29
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:25:29
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:25:30
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb247a210>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:25:30
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:25:30
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:25:45
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:25:45
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119a6f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:25:45
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:25:45
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:26:45
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:26:46
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b6950>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:26:46
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:26:46
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:27:37
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:27:37
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119a690>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:27:37
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:27:37
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:28:37
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:28:37
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b6ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:28:37
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:28:37
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:28:52
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:28:52
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119b610>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:28:52
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:28:52
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:29:54
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:29:54
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb125f630>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:29:54
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:29:54
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:30:54
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:30:54
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb127c8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:30:54
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:30:54
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:31:54
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:31:54
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb127c070>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:31:54
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:31:54
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:45:48
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:45:48
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb2421eb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:45:48
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:45:48
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:46:48
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:46:49
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb2425350>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:46:49
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:46:49
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:47:49
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:47:49
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb2425670>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:47:49
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:47:49
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:48:01
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:48:01
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119b5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:48:01
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:48:01
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:49:02
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:49:02
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119b0f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:49:02
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:49:02
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:50:02
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:50:02
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b7030>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:50:02
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:50:02
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:51:02
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:51:02
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b7c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:51:02
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:51:02
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/27 17:52:02
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:52:02
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b7730>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/27 17:52:02
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/27 17:52:02
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:19:49
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:19:49
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23d6ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:19:49
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:19:49
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:20:49
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:20:50
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23da9f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:20:50
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:20:50
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:21:50
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:21:50
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23d6250>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:21:50
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:21:50
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:22:50
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:22:50
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23da450>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:22:50
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:22:50
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:23:50
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:23:50
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23d6e90>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:23:50
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:23:50
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:24:50
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:24:50
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23daa90>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:24:50
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:24:50
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:25:17
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:25:17
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1b59610>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:25:17
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:25:17
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:26:17
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:26:18
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1b74870>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:26:18
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:26:18
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:27:18
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:27:18
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1b74110>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:27:18
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:27:18
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:28:18
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:28:18
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb09d73d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:28:18
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:28:18
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:29:18
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:29:18
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1b74650>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:29:18
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:29:18
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:30:18
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:30:19
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1175670>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:30:19
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:30:19
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:31:19
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:31:19
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1191890>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:31:19
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:31:19
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:32:19
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:32:19
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1191170>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:32:19
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:32:19
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:33:19
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:33:19
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb092c3f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:33:19
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:33:19
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:34:19
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:34:19
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11916f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:34:19
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:34:20
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:35:20
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:35:20
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb092c370>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:35:20
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:35:20
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:36:20
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:36:20
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb092cc90>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:36:20
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:36:20
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:37:20
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:37:20
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1191530>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:37:20
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:37:20
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:38:20
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:38:20
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1191f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:38:20
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:38:20
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:38:58
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:38:58
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119c5b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:38:58
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:38:58
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:39:58
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:39:58
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119ca50>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:39:58
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:39:58
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:40:58
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:40:58
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119cc30>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:40:58
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:40:58
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:41:58
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:41:59
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b6670>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:41:59
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:41:59
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:42:59
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:42:59
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119cd30>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:42:59
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:42:59
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:43:59
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:43:59
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b6750>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:43:59
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:43:59
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:44:59
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:44:59
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb09353b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:44:59
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:44:59
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:45:59
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:45:59
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b6290>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:45:59
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:45:59
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:47:00
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:47:00
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119cbd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:47:00
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:47:00
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:48:00
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:48:00
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb09355f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:48:00
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:48:00
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:49:00
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:49:00
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb0935c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:49:00
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:49:00
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:50:00
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:50:00
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119cc30>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:50:00
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:50:00
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:51:00
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:51:02
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b66b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:51:02
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:51:02
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:52:02
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:52:02
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb0935810>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:52:02
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:52:02
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:53:02
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:53:02
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b6870>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:53:02
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:53:02
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:54:02
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:54:02
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119c490>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:54:02
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:54:02
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:55:02
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:55:02
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb0935750>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:55:02
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:55:02
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:56:02
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:56:04
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119cd70>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:56:04
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:56:04
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:57:04
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:57:04
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b6df0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:57:04
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:57:04
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:58:04
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:58:04
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb0935330>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:58:04
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:58:04
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 09:59:04
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:59:04
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb0935910>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 09:59:04
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 09:59:04
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:00:04
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:00:05
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b66f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:00:05
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:00:05
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:01:05
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:01:05
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119c810>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:01:05
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:01:05
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:02:05
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:02:05
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb09358b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:02:05
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:02:05
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:03:05
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:03:05
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b67b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:03:05
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:03:05
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:04:05
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:04:06
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb0935810>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:04:06
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:04:06
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:05:06
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:05:06
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb09353f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:05:06
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:05:06
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:06:06
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:06:06
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119cd10>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:06:06
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:06:06
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:07:06
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:07:06
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb0935650>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:07:06
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:07:06
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:08:06
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:08:06
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb0935b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:08:06
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:08:06
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:09:06
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:09:07
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b63f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:09:07
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:09:07
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:10:07
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:10:07
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b6350>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:10:07
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:10:07
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:11:07
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:11:07
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb09356d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:11:07
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:11:07
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:12:07
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:12:07
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb0935650>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:12:07
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:12:07
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:13:07
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:13:07
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119c4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:13:07
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:13:07
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:14:07
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:14:08
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb0935570>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:14:08
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:14:08
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:15:08
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:15:08
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb0935b30>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:15:08
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:15:08
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:16:08
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:16:08
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b6730>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:16:08
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:16:08
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:17:08
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:17:08
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11b6370>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:17:08
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:17:08
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:18:08
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:18:08
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb09352b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:18:08
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:18:08
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:19:08
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:19:09
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb09355d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:19:09
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:19:09
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:20:09
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:20:09
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb119c630>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:20:09
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:20:09
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:24:49
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:24:50
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb238e3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:24:50
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:24:50
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:25:50
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:25:50
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23999d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:25:50
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:25:50
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:26:50
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:26:50
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb2399a50>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:26:50
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:26:50
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:27:50
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:27:50
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb231f0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:27:50
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:27:50
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:28:51
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:28:51
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb231f6b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:28:51
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:28:51
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:29:51
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:29:51
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb2399e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:29:51
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:29:51
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:30:51
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:30:51
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb231fb30>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:30:51
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:30:51
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:31:51
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:31:51
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb239c050>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:31:51
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:31:51
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:32:51
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:32:51
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb2399930>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:32:51
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:32:51
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:33:52
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:33:52
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb231fe70>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:33:52
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:33:52
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:34:52
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:34:52
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb231f8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:34:52
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:34:52
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:35:52
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:35:52
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb239c470>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:35:52
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:35:52
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ***********************************************************************************
Fecha / Hora : 2022/12/28 10:55:57
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:55:57
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23d7ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:55:57
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:55:57
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:56:57
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:56:58
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23db990>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:56:58
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:56:58
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:57:58
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:57:58
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23d71d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:57:58
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:57:58
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:58:28
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:58:28
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1174510>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:58:28
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:58:28
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 10:59:28
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:59:28
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1174a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 10:59:28
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 10:59:28
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:00:28
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:00:28
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1174cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:00:28
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:00:28
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:01:34
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:01:34
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb244d8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:01:34
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:01:34
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:02:34
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:02:34
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb0a16ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:02:34
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:02:34
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:03:34
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:03:34
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb244dfb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:03:34
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:03:35
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:04:35
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:04:35
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1276090>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:04:35
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:04:35
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:05:11
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:05:11
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11cb5f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:05:11
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:05:11
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:06:11
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:06:12
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb11cb6f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:06:12
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:06:12
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:06:34
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:06:34
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1b37730>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:06:34
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:06:34
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:07:34
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:07:35
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1b51c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:07:35
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:07:35
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:08:35
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:08:35
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1b51190>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:08:35
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:08:35
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:09:35
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:09:35
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb09d4490>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:09:35
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:09:35
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:10:35
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:10:35
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1b51670>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:10:35
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:10:35
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:11:35
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:11:35
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb09d4410>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:11:35
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:11:35
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:12:35
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:12:36
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb09d4d30>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:12:36
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:12:36
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:13:36
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:13:36
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1b51570>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:13:36
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:13:36
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:14:36
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:14:36
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1b51f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:14:36
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:14:36
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:15:36
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:15:36
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb09d45d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:15:36
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:15:36
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:16:36
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:16:36
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb1b51e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:16:36
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:16:36
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ***********************************************************************************
Fecha / Hora : 2022/12/28 11:22:52
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:22:52
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23aae30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:22:52
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:22:52
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:23:52
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:23:52
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23ae910>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:23:52
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:23:52
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:24:52
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:24:53
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23aa150>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:24:53
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:24:53
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:25:53
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:25:53
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23ae370>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:25:53
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:25:53
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:26:53
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:26:53
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23aedb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:26:53
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:26:53
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:27:53
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:27:53
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23b3250>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:27:53
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:27:53
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:28:53
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:28:53
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23b3fb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:28:53
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:28:53
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:29:53
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:29:54
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23b3750>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:29:54
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:29:54
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:30:54
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:30:54
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23aec70>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:30:54
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:30:54
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ***********************************************************************************
Fecha / Hora : 2022/12/28 11:41:44
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:41:44
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23eeb50>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:41:44
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:41:44
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:42:45
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:42:45
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23f2290>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:42:45
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:42:45
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:43:45
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:43:45
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23eeeb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:43:45
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:43:45
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:44:45
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:44:45
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23f2710>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:44:45
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:44:45
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2022/12/28 11:45:45
Leyendo token...
***********************************************************************************
Fecha / Hora : 2022/12/28 11:45:45
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb23f2e90>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2022/12/28 11:45:45
Chequear configuracion...
***********************************************************************************
<<<<<<< HEAD
Fecha / Hora : 2021/09/21 19:21:14
Error : ERROR - archivo : reporte.py - linea : 102 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 13:54:17
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 13:54:17
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586cad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 13:54:17
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 13:54:17
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 13:55:17
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 13:55:18
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586c950>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 13:55:20
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 13:55:20
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 13:56:20
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 13:56:20
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890a70>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 13:56:20
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 13:56:20
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 13:57:20
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 13:57:20
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586c1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 13:57:20
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 13:57:20
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 13:58:20
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 13:58:21
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890b70>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 13:58:21
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 13:58:21
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 13:59:21
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 13:59:21
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58908b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 13:59:21
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 13:59:21
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:00:21
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:00:21
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890510>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:00:21
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:00:21
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:01:21
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:01:22
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:01:22
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:01:22
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:02:22
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:02:22
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586cef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:02:22
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:02:22
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:03:22
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:03:22
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58ac7b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:03:22
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:03:22
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:04:22
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:04:22
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586ca50>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:04:22
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:04:22
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:05:22
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:05:23
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890db0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:05:23
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:05:23
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:06:23
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:06:23
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58ac7b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:06:23
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:06:23
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:07:25
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:07:26
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:07:26
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:07:26
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:08:26
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:08:26
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890cf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:08:26
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:08:26
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:09:26
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:09:26
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586c190>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:09:26
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:09:26
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:10:26
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:10:26
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58ac7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:10:26
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:10:26
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:11:27
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:11:28
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586cc30>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:11:28
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:11:28
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:12:28
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:12:28
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:12:28
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:12:28
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:13:28
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:13:28
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58ac170>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:13:28
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:13:28
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:14:28
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:14:29
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890ff0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:14:29
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:14:29
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:15:29
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:15:29
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890e30>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:15:29
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:15:29
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:16:29
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:16:29
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586cb90>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:16:29
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:16:29
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:17:29
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:17:29
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58ac750>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:17:29
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:17:29
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:18:30
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:18:30
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586cdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:18:30
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:18:30
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:19:30
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:19:30
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:19:30
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:19:30
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:20:30
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:20:30
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58ac4b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:20:30
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:20:30
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:21:30
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:21:30
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890930>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:21:30
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:21:31
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:22:31
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:22:31
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890e30>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:22:31
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:22:31
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:23:31
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:23:31
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586cc70>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:23:31
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:23:31
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:24:31
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:24:31
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58ac210>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:24:31
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:24:31
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:25:31
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:25:32
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586c1f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:25:32
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:25:32
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:26:32
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:26:32
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:26:32
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:26:32
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:27:32
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:27:32
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58ac9b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:27:32
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:27:32
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:28:32
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:28:32
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890850>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:28:32
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:28:32
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:29:32
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:29:33
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890b70>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:29:33
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:29:33
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:30:33
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:30:33
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586ced0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:30:33
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:30:33
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:31:33
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:31:33
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58ac7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:31:33
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:31:33
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:32:33
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:32:33
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586cbd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:32:33
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:32:33
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:33:33
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:33:34
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:33:34
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:33:34
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:34:34
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:34:34
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58ac7b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:34:34
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:34:34
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:35:34
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:35:34
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890410>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:35:34
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:35:34
=======
Fecha / Hora : 2022/12/28 11:45:45
>>>>>>> fe8d0113df44088e4aeeb400bc7bf002bcfdfcb7
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:38:35
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:38:35
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58ac750>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:38:35
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:38:35
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:39:35
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:39:35
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586c970>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:39:35
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:39:35
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:40:35
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:40:36
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890c30>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:40:36
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:40:36
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:41:36
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:41:37
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58ac670>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:41:37
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:41:37
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:42:37
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:42:37
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890570>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:42:37
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:42:37
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:43:38
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:43:38
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890970>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:43:38
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:43:38
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:44:38
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:44:38
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586ca50>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:44:38
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:44:38
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:45:38
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:45:38
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58ac730>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:45:38
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:45:38
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:46:38
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:46:39
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586c9b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:46:39
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:46:39
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:47:39
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:47:39
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:47:39
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:47:39
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:48:39
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:48:39
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58ac710>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:48:39
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:48:39
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:49:39
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:49:39
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890450>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:49:39
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:49:39
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:50:40
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:50:40
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5890db0>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:50:40
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:50:40
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:51:40
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:51:40
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb586cd30>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:51:40
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:51:40
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
***********************************************************************************
Fecha / Hora : 2023/02/24 14:52:40
Leyendo token...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:52:40
Error : ERROR - archivo : reporte.py - linea : 53 - mensaje : HTTPConnectionPool(host='hbl.jphlions.com', port=3600): Max retries exceeded with url: /api/login-nitro4/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb58ac130>: Failed to establish a new connection: [Errno 111] Connection refused'))
***********************************************************************************
Fecha / Hora : 2023/02/24 14:52:40
Chequear configuracion...
***********************************************************************************
Fecha / Hora : 2023/02/24 14:52:40
Error : ERROR - archivo : reporte.py - linea : 105 - mensaje : Value for header {Token: 0} must be of type str or bytes, not <class 'int'>
